POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5kb2VAZ21haWwuY29tIiwiZXhwIjoxNzM1OTEzMzA1LCJ1c2VySWQiOjF9.VNIoyZmHhCGcBXJA5L0x-_4xSQOx1L2OxCm1e53zIc8

{
    "name": "Another Test",
    "description": "Another Testing event",
    "location": "test",
    "dateTime": "2024-12-30T20:57:50.000Z"
}
